version: '3.8'

services:
  youtube_downloader:
    image: asifrehan12/youtube-video-download-app:latest 
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
